name: Release RizzLang

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.os == 'windows-latest' && 'build/Release/rizz.exe' || 'build/rizz*' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
